import { createFileRoute } from "@tanstack/react-router";
import { Award, BookOpen, Scissors, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { whatsappUrl } from "@/lib/salon";
import academySrc from "@/assets/sachin-academy.jpg";

export const Route=createFileRoute("/academy")({head:()=>({meta:[{title:"Salon Academy in Silvassa | Sachin Salon"},{name:"description",content:"Learn professional haircutting, hairstyling, beauty, makeup and salon skills at Sachin Salon Academy in Silvassa."},{property:"og:title",content:"Sachin Salon Academy in Silvassa"},{property:"og:description",content:"Hands-on salon skills training for aspiring beauty professionals."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{property:"og:url",content:"/academy"}],links:[{rel:"canonical",href:"/academy"}]}),component:AcademyPage});

const courses=[[Scissors,"Hair cutting & styling","Learn foundations, sectioning, cutting, finishing and contemporary salon styling."],[Sparkles,"Beauty & make-up","Build practical skills in skin preparation, make-up looks and client-ready finishing."],[BookOpen,"Salon essentials","Understand consultation, hygiene, tools, service flow and professional client care."]];
function AcademyPage(){return <SiteShell><section className="relative min-h-[520px] overflow-hidden bg-ink text-ink-foreground"><img src={academySrc} alt="Students learning salon skills at Sachin Salon Academy" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-linear-to-r from-ink via-ink/80 to-transparent"/><div className="relative mx-auto flex min-h-[520px] max-w-6xl items-center px-4 py-16 sm:px-6"><div className="max-w-2xl"><p className="text-xs font-bold uppercase text-primary">Sachin Salon Academy</p><h1 className="mt-4 text-4xl font-extrabold sm:text-6xl">Learn salon skills with hands-on guidance</h1><p className="mt-5 max-w-xl text-lg leading-8 text-ink-muted">Training for aspiring professionals who want practical experience in hair, beauty, make-up and salon care.</p><Button asChild size="lg" className="mt-8"><a href={whatsappUrl("Hello Sachin Salon Academy, I would like to know about salon training courses.")} target="_blank" rel="noreferrer">Ask about courses</a></Button></div></div></section><section className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="text-center"><Award className="mx-auto h-9 w-9 text-primary"/><h2 className="mt-4 text-3xl font-extrabold">Skills you can learn</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3">{courses.map(([Icon,title,text])=><article key={String(title)} className="rounded-lg border border-border bg-card p-7"><Icon className="h-7 w-7 text-primary"/><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section></SiteShell>}