import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";
import logo from "@/assets/sachin-salon-logo.png.asset.json";
export const Route=createFileRoute("/auth")({head:()=>({meta:[{title:"Owner Login | Sachin Unisex Salon"},{name:"description",content:"Secure owner access for Sachin Unisex Salon."},{name:"robots",content:"noindex"},{property:"og:title",content:"Owner Login"},{property:"og:description",content:"Secure owner access."},{property:"og:url",content:"/auth"}]}),component:AuthPage});
function AuthPage(){const nav=useNavigate();const [mode,setMode]=useState<"signin"|"signup"|"forgot">("signin");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");if(mode==="forgot"){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setMessage(error?.message??"Check your email for a reset link.");setBusy(false);return;}if(mode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin}});setMessage(error?.message??(data.session?"Account created.":"Check your email to confirm your account."));if(data.session)nav({to:"/dashboard"});}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else nav({to:"/dashboard"});}setBusy(false)}async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error)setMessage(result.error.message);else if(!result.redirected)nav({to:"/dashboard"})}return <main className="grid min-h-screen place-items-center bg-secondary px-4"><div className="w-full max-w-md rounded-lg bg-card p-7 shadow-xl"><a href="/" className="mb-6 flex items-center gap-3"><img src={logo.url} alt="Sachin Unisex Salon" className="h-12 w-12 rounded-full"/><span className="font-extrabold">Sachin Unisex Salon</span></a><h1 className="text-2xl font-extrabold">{mode==="signin"?"Owner sign in":mode==="signup"?"Create owner account":"Reset password"}</h1><p className="mt-2 text-sm text-muted-foreground">The first account created receives administrator access.</p><form onSubmit={submit} className="mt-6 space-y-4"><Input type="email" placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)} required/>{mode!=="forgot"&&<Input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/>}<Button className="w-full" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":mode==="signup"?"Create account":"Send reset link"}</Button></form>{mode!=="forgot"&&<><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>or<span className="h-px flex-1 bg-border"/></div><Button variant="outline" className="w-full" onClick={google}>Continue with Google</Button></>}{message&&<p className="mt-4 rounded-md bg-secondary p-3 text-sm">{message}</p>}<div className="mt-5 flex flex-wrap gap-4 text-xs font-semibold"><button onClick={()=>setMode(mode==="signup"?"signin":"signup")}>{mode==="signup"?"Sign in instead":"Create first account"}</button><button onClick={()=>setMode(mode==="forgot"?"signin":"forgot")}>{mode==="forgot"?"Back to sign in":"Forgot password?"}</button></div></div></main>}
