import { createFileRoute } from "@tanstack/react-router";
import { Check, Gift } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { useSalonContent } from "@/components/salon/Content";
import { whatsappUrl } from "@/lib/salon";
import membershipSrc from "@/assets/sachin-membership-table.png";

export const Route=createFileRoute("/membership")({head:()=>({meta:[{title:"Salon Membership in Silvassa | Sachin Salon"},{name:"description",content:"Ask about Sachin Unisex Salon membership privileges, seasonal offers and personalised care benefits in Silvassa."},{property:"og:title",content:"Sachin Salon Membership"},{property:"og:description",content:"More value and personalised care with every salon visit."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{property:"og:url",content:"/membership"}],links:[{rel:"canonical",href:"/membership"}]}),component:MembershipPage});

function MembershipPage(){const c=useSalonContent(); return <SiteShell><section className="bg-ink text-ink-foreground"><div className="mx-auto max-w-6xl px-4 py-12 text-center sm:px-6"><Gift className="mx-auto h-10 w-10 text-primary"/><p className="mt-5 text-xs font-bold uppercase text-primary">Sachin privileges</p><img src={membershipSrc} alt="Sachin Salon membership comparison table" width={1600} height={1000} className="mt-7 w-full rounded-lg border border-ink-border shadow-xl" /><Button asChild size="lg" className="mt-8"><a href={whatsappUrl("Hello Sachin Unisex Salon, I would like to know about membership and offers.")} target="_blank" rel="noreferrer">Ask about membership</a></Button><h1 className="mx-auto mt-10 max-w-3xl text-4xl font-extrabold sm:text-6xl">Good hair days, with a little more.</h1><p className="mx-auto mt-6 max-w-xl leading-7 text-ink-muted">{c.pages.membership}</p></div></section><section className="mx-auto max-w-4xl px-4 py-16 sm:px-6"><h2 className="text-center text-3xl font-extrabold">Member benefits</h2><div className="mt-10 grid gap-3 md:grid-cols-3">{[["Seasonal offers","Access selected salon offers throughout the year."],["Personal care","Recommendations shaped around your hair and grooming routine."],["Priority updates","Hear about new services and appointment openings."]].map(([t,d])=><article key={t} className="rounded-lg border border-border p-6"><Check className="text-primary"/><h3 className="mt-5 font-extrabold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></article>)}</div></section></SiteShell>}