import { createFileRoute } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { useSalonContent } from "@/components/salon/Content";
import { whatsappUrl } from "@/lib/salon";
import womenSrc from "@/assets/womens-hair-styling.jpg";
import shampooSrc from "@/assets/product-nourishing-shampoo.jpg";
import maskSrc from "@/assets/product-repair-mask.jpg";
import serumSrc from "@/assets/product-smoothing-serum.jpg";
import conditionerSrc from "@/assets/product-colour-conditioner.jpg";
const women = { url: womenSrc };
const productImages=[shampooSrc,maskSrc,serumSrc,conditionerSrc];
export const Route=createFileRoute("/products")({head:()=>({meta:[{title:"Professional Hair Products in Silvassa | Sachin Salon"},{name:"description",content:"Discover salon-recommended shampoo, masks, serum and colour care at Sachin Unisex Salon in Silvassa."},{property:"og:title",content:"Hair Care Products | Sachin Unisex Salon"},{property:"og:description",content:"Salon-selected care for healthier-looking hair."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{property:"og:url",content:"/products"}],links:[{rel:"canonical",href:"/products"}]}),component:ProductsPage});
function ProductsPage(){const c=useSalonContent(); return <SiteShell><section className="mx-auto grid max-w-6xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-2"><div className="self-center"><p className="text-xs font-bold uppercase text-primary">Salon favourites</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Care that continues at home</h1><p className="mt-5 max-w-lg leading-7 text-muted-foreground">Ask our team which professional routine best suits your hair, scalp and colour goals.</p></div><img src={women.url} alt="Healthy styled hair at Sachin Unisex Salon" className="h-96 w-full rounded-lg object-cover" /></section><section className="bg-secondary"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><h2 className="mb-8 text-3xl font-extrabold">Shop by need</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{c.products.map((p,i)=><article key={p.name} className="overflow-hidden rounded-lg bg-card"><img src={productImages[i%productImages.length]} alt={p.name} width={912} height={912} loading="lazy" className="aspect-square w-full object-cover"/><div className="p-5"><p className="text-xs font-semibold uppercase text-muted-foreground">{p.brand}</p><h2 className="mt-2 min-h-12 font-extrabold">{p.name}</h2><p className="mt-3 font-bold">₹{p.price}</p><Button asChild variant="outline" className="mt-5 w-full"><a href={whatsappUrl(`Hello Sachin Unisex Salon, I am interested in ${p.name}.`)} target="_blank" rel="noreferrer">Enquire</a></Button></div></article>)}</div></div></section></SiteShell>}
