import { createFileRoute } from "@tanstack/react-router";
import { ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { useSalonContent } from "@/components/salon/Content";
import { whatsappUrl } from "@/lib/salon";
import womenSrc from "@/assets/womens-hair-styling.jpg";
const women = { url: womenSrc };
export const Route=createFileRoute("/products")({head:()=>({meta:[{title:"Professional Hair Products in Silvassa | Sachin Salon"},{name:"description",content:"Discover salon-recommended shampoo, masks, serum and colour care at Sachin Unisex Salon in Silvassa."},{property:"og:title",content:"Hair Care Products | Sachin Unisex Salon"},{property:"og:description",content:"Salon-selected care for healthier-looking hair."},{property:"og:url",content:"/products"}],links:[{rel:"canonical",href:"/products"}]}),component:ProductsPage});
function ProductsPage(){const c=useSalonContent(); return <SiteShell><section className="mx-auto grid max-w-6xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-2"><div className="self-center"><p className="text-xs font-bold uppercase text-primary">Salon favourites</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Care that continues at home</h1><p className="mt-5 max-w-lg leading-7 text-muted-foreground">Ask our team which professional routine best suits your hair, scalp and colour goals.</p></div><img src={women.url} alt="Healthy styled hair at Sachin Unisex Salon" className="h-96 w-full rounded-lg object-cover" /></section><section className="bg-secondary"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><h2 className="mb-8 text-3xl font-extrabold">Shop by need</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{c.products.map((p,i)=><article key={p.name} className="rounded-lg bg-card p-5"><div className="grid aspect-square place-items-center rounded-md bg-warm"><ShoppingBag className="h-14 w-14 text-primary" strokeWidth={1.2}/></div><p className="mt-5 text-xs font-semibold uppercase text-muted-foreground">{p.brand}</p><h2 className="mt-2 min-h-12 font-extrabold">{p.name}</h2><p className="mt-3 font-bold">₹{p.price}</p><Button asChild variant="outline" className="mt-5 w-full"><a href={whatsappUrl(`Hello Sachin Unisex Salon, I am interested in ${p.name}.`)} target="_blank" rel="noreferrer">Enquire</a></Button></article>)}</div></div></section></SiteShell>}
