import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { useSalonContent } from "@/components/salon/Content";
import { whatsappUrl } from "@/lib/salon";
export const Route = createFileRoute("/services")({ head:()=>({ meta:[{title:"Salon Services & Prices in Silvassa | Sachin Salon"},{name:"description",content:"Explore affordable haircuts, hair colour, spa, facials and grooming services for women and men at Sachin Unisex Salon, Silvassa."},{property:"og:title",content:"Salon Services in Silvassa | Sachin Salon"},{property:"og:description",content:"Hair and beauty services with clear starting prices."},{property:"og:url",content:"/services"}],links:[{rel:"canonical",href:"/services"}]}), component: ServicesPage });
function ServicesPage(){const c=useSalonContent(); const [tab,setTab]=useState("Women"); const categories=["Women","Men","Unisex"]; return <SiteShell><section className="bg-warm"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><p className="text-xs font-bold uppercase text-primary">Expert care</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Services for every style</h1><p className="mt-4 max-w-2xl text-muted-foreground">Haircuts, colour, styling, spa and grooming—delivered with personal attention in Silvassa.</p></div></section><section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="mb-8 flex gap-2">{categories.map(x=><Button key={x} variant={tab===x?"default":"secondary"} onClick={()=>setTab(x)}>{x}</Button>)}</div><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-2">{c.services.filter(s=>s.category===tab).map(s=><article key={s.name} className="grid grid-cols-[minmax(0,1fr)_auto] gap-5 bg-background p-6"><div className="min-w-0"><h2 className="font-extrabold">{s.name}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{s.description}</p></div><div className="text-right"><p className="font-extrabold">₹{s.price}</p><p className="text-xs text-muted-foreground">onwards</p></div></article>)}</div><div className="mt-10 rounded-lg bg-ink p-7 text-ink-foreground sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-extrabold">Ready for a fresh look?</h2><p className="mt-2 text-sm text-ink-muted">Message us for availability and a personalised quote.</p></div><Button asChild className="mt-5 sm:mt-0"><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle/>Book on WhatsApp</a></Button></div></section></SiteShell>}
