import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteShell } from "@/components/salon/SiteShell";
import { useSalonContent } from "@/components/salon/Content";
import { whatsappUrl } from "@/lib/salon";

export const Route = createFileRoute("/services")({ head:()=>({ meta:[{title:"Salon Services & Prices in Silvassa | Sachin Salon"},{name:"description",content:"Explore main men, women and family salon service categories at Sachin Unisex Salon, Silvassa."},{property:"og:title",content:"Salon Services in Silvassa | Sachin Salon"},{property:"og:description",content:"Hair, beauty, grooming and family salon packages with clear starting prices."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},{property:"og:url",content:"/services"}],links:[{rel:"canonical",href:"/services"}]}), component: ServicesPage });

function ServicesPage(){const c=useSalonContent(); const [tab,setTab]=useState("Women"); const categories=["Women","Men","Family"]; const shown=c.services.filter(s=>s.category===tab); return <SiteShell><section className="bg-warm"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><p className="text-xs font-bold uppercase text-primary">Service catalogue</p><h1 className="mt-3 text-4xl font-extrabold sm:text-5xl">Main salon categories</h1><p className="mt-4 max-w-2xl text-muted-foreground">Choose women, men or family and message us for the latest detailed menu and appointment timing.</p></div></section><section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="mb-8 flex flex-wrap gap-2">{categories.map(x=><Button key={x} variant={tab===x?"default":"secondary"} onClick={()=>setTab(x)}>{x}</Button>)}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{shown.map(s=><article key={`${s.category}-${s.name}`} className="rounded-lg border border-border bg-card p-6"><div className="grid min-h-28 grid-cols-[minmax(0,1fr)_auto] gap-4"><div><h2 className="text-xl font-extrabold">{s.name}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{s.description}</p></div><div className="text-right"><p className="font-extrabold">{s.price ? `₹${s.price}` : "Ask"}</p><p className="text-xs text-muted-foreground">onwards</p></div></div><Button asChild variant="outline" className="mt-6 w-full"><a href={whatsappUrl(`Hello Sachin Unisex Salon, I want to know about ${tab} ${s.name}.`)} target="_blank" rel="noreferrer"><MessageCircle/>Enquire</a></Button></article>)}</div><div className="mt-10 rounded-lg bg-ink p-7 text-ink-foreground sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-extrabold">Need the full price menu?</h2><p className="mt-2 text-sm text-ink-muted">Message us for current rates, combos and availability.</p></div><Button asChild className="mt-5 sm:mt-0"><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle/>Book on WhatsApp</a></Button></div></section></SiteShell>}